name = "journalizer"
main = "src/index.ts"
compatibility_date = "2026-02-02"
compatibility_flags = ["nodejs_compat"]

# D1 Database
[[d1_databases]]
binding = "DB"
database_name = "journalizer-db"
database_id = "d95a062f-d884-4873-a6f2-e795bf63e764"
migrations_dir = "src/db/migrations"

# R2 Media Storage
[[r2_buckets]]
binding = "MEDIA"
bucket_name = "journalizer-media"

# KV Sessions & Cache
[[kv_namespaces]]
binding = "KV"
id = "1c7eacd579fd4b6aa1b153fab4f9807a"

[triggers]
crons = ["*/15 * * * *"]

[vars]
ENVIRONMENT = "development"
